CREATE TABLE IF NOT EXISTS model_call_records (
  id BIGINT NOT NULL AUTO_INCREMENT,
  record_type VARCHAR(32) NOT NULL DEFAULT 'stream_final',
  chain VARCHAR(32) NOT NULL DEFAULT 'main_chat',
  user_id VARCHAR(128) NOT NULL DEFAULT '',
  client_msg_id VARCHAR(128) NOT NULL DEFAULT '',
  request_id VARCHAR(128) NOT NULL DEFAULT '',
  upstream_request_id VARCHAR(128) NOT NULL DEFAULT '',
  provider VARCHAR(32) NOT NULL DEFAULT '',
  provider_label VARCHAR(64) NOT NULL DEFAULT '',
  provider_slot VARCHAR(64) NOT NULL DEFAULT '',
  key_slot VARCHAR(96) NOT NULL DEFAULT '',
  model VARCHAR(64) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT '',
  fallback_reason VARCHAR(64) NOT NULL DEFAULT '',
  error_kind VARCHAR(64) NOT NULL DEFAULT '',
  http_status INT NOT NULL DEFAULT 0,
  attempt INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL DEFAULT 0,
  tier VARCHAR(32) NOT NULL DEFAULT '',
  image_count INT NOT NULL DEFAULT 0,
  prompt_has_images BOOLEAN NOT NULL DEFAULT FALSE,
  forced_search BOOLEAN NOT NULL DEFAULT FALSE,
  search_strategy VARCHAR(64) NOT NULL DEFAULT '',
  reasoning_effort VARCHAR(32) NOT NULL DEFAULT '',
  thinking_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  thinking_budget INT NOT NULL DEFAULT 0,
  open_ms BIGINT NOT NULL DEFAULT -1,
  request_to_open_ms BIGINT NOT NULL DEFAULT -1,
  first_visible_ms BIGINT NOT NULL DEFAULT -1,
  upstream_first_visible_ms BIGINT NOT NULL DEFAULT -1,
  total_ms BIGINT NOT NULL DEFAULT -1,
  input_tokens INT NOT NULL DEFAULT 0,
  output_tokens INT NOT NULL DEFAULT 0,
  total_tokens INT NOT NULL DEFAULT 0,
  reasoning_tokens INT NOT NULL DEFAULT 0,
  cached_tokens INT NOT NULL DEFAULT 0,
  search_count INT NOT NULL DEFAULT 0,
  reply_chars INT NOT NULL DEFAULT 0,
  client_disconnected BOOLEAN NOT NULL DEFAULT FALSE,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (id),
  KEY idx_model_call_records_created (created_at),
  KEY idx_model_call_records_provider_created (provider, provider_label, created_at),
  KEY idx_model_call_records_user_created (user_id, created_at),
  KEY idx_model_call_records_client_msg (client_msg_id),
  KEY idx_model_call_records_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
